### ISSUE TITLE
browsing adding crashes on Mac

### ISSUE THREAD

**Issue by cmbarton** [daattali/addinslist#127] opened 2021-06-28 22:29 UTC
If I try to use this to browse addins, a window opens, then it disappears, and I get this error:

```
Listening on http://127.0.0.1:5157
pandoc: ~/Library/Application Support/addinsrepo/addins.md: openBinaryFile: does not exist (No such file or directory)
Warning: Error in : pandoc document conversion failed with error 1
  57: stop
  56: rmarkdown::pandoc_convert
  55: update_addins_file
  54: update_addins_list
  53: update_addins_list_values
  52: refresh_list
  51: <Anonymous>
  49: server
Error : pandoc document conversion failed with error 1
```

FYI, I'm using the most recent Mac OS, most recent R, and a recent version of Rstudio (Version 1.4.1717)

**Comment by daattali** [comment] 2021-06-28 23:08
Looks like a duplicate of https://github.com/daattali/addinslist/issues/124

Please install the latest dev version (not from CRAN) and try again

**Comment by cmbarton** [comment] 2021-06-28 23:18
That does the trick. Thanks.

**Comment by daattali** [comment] 2021-06-29 08:13
In the future, before opening an issue in any project, always try the latest dev version :)

**Closed by daattali** 2021-06-29 08:13 UTC

**Comment by cmbarton** [comment] 2021-06-29 13:50
I checked the issue tracker and didn’t find it. That’s why I opened a new one. Sorry for the hassle

Michael Barton

...Sent from my iPad
